kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: inventory-cluster
nodes:
- role: control-plane
  extraPortMappings:
  # Only frontend exposed externally via LoadBalancer
  - containerPort: 30000
    hostPort: 3000
    protocol: TCP
